### ISSUE TITLE
 OpenMP not detected on Mac (Help from Mac users kindly needed!)

### ISSUE THREAD

**Issue by Asquidy** [lrberge/fixest#63]
Hi, I'm trying to use fixest with multiple threads but it doesn't work. See the code below. Note that I do have OpenMP installed and it works on other R packages such as data.table. Any thoughts on why this may happen?
```

> library(fixest)
> fenegbin(Euros ~ log(dist_km)|Origin+Destination+Product+Year, trade, nthreads = 2)
Negative Binomial ML estimation, Dep. Var.: Euros
Observations: 38,325 
Fixed-effects: Origin: 15,  Destination: 15,  Product: 20,  Year: 10
Standard-errors: Clustered (Origin) 
             Estimate Std. Error z value  Pr(>|z|)    
log(dist_km)  -1.7108   0.166347 -10.284 < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Over-dispersion parameter: theta = 0.5487878  
Log-likelihood:  -646,586.98   Adj. Pseudo-R2: 0.03464 
           BIC: 1,293,796.64     Squared Cor.: 0.43761 
Warning message:
In fixest_env(fml = fml, data = data, family = famil...:
 OpenMP not detected: cannot use 2 threads, single-threaded mode instead. 
```

**Comment by lrberge** [comment]
Hi, that looks very platform specific. Unfortunately, I have no access to MAC so it'll be difficult to debug.

I've googled around and it may be a flag problem.  The flag _OPENMP isn't there on your install. 

Does the package [fst](https://cran.r-project.org/web/packages/fst/index.html) have multi-threading enabled?

Related issues:
https://github.com/fstpackage/fst/issues/242
https://github.com/Rdatatable/data.table/issues/4417
https://github.com/Rdatatable/data.table/issues/4410

**Comment by Asquidy** [comment]
Thanks, fst doesn't find OpenMP either. Will let you know if I find a solution.

**Comment by lrberge** [comment]
Hi, did you manage to find a solution?

**Comment by Asquidy** [comment]
Unfortunately not

**Comment by lrberge** [comment]
OK, thanks. I'm changing the title (don't know if it'll help though :-)).

**Comment by grantmcdermott** [comment]
I too am not on Mac. But I recall that a related issue came up on the data.table GH repo. TL;DR is that OpenMP wasn't natively supported by MacOS toolchain used by R 4.0.0+.

See here and links therein: https://github.com/Rdatatable/data.table/issues/4348

**Comment by Asquidy** [comment]
@grantmcdermott thanks for this link. Weirdly, data.table works just fine for me when I change the Makevars file, but fixest doesn't.

**Comment by lrberge** [comment]
I think the guys from `data.table` have applied patches to make it work. 

But I don't know enough on these topics really. Further I don't think it's worth the extra legwork if next versions of R will fix it (which is really great news and makes sense given the prominence of OpenMP).

**Comment by pbaylis** [comment]
I just got OpenMP working for on my Macbook Pro `data.table` (following their [instructions](https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac)), but not `fst` or `fixest`. According to this [thread](https://github.com/fstpackage/fst/issues/250) there is some way to do it in `fst` but I gave up after five minutes. The same thread also indicates that the `data.table` people got it working using patches.

But yeah, if R is going to fix this anyway soon, doesn't seem worth the extra effort.

**Comment by lrberge** [comment]
And here's the ad hoc DT PR https://github.com/Rdatatable/data.table/pull/3984

**Comment by adamaltmejd** [comment]
Think I got it working with the following Makevars file. For it to work you will first need to run (if you haven't already). Only tested with R installed with Homebrew, not the 4.1 binary.

```
xcode-select --install
brew install llvm gcc gettext libomp
```

Install homebrew here: https://brew.sh

~/.R/Makevars
```
XC_LOC:=$(shell xcrun --show-sdk-path)
LLVM_LOC:=$(shell brew --prefix llvm)
GCC_LOC:=$(shell brew --prefix gcc)
GETTEXT_LOC:=$(shell brew --prefix gettext)
OMP_LOC:=$(shell brew --prefix libomp)

CC=$(LLVM_LOC)/bin/clang
CXX=$(LLVM_LOC)/bin/clang++
CXX11=$(LLVM_LOC)/bin/clang++
CXX14=$(LLVM_LOC)/bin/clang++
CXX17=$(LLVM_LOC)/bin/clang++
CXX1X=$(LLVM_LOC)/bin/clang++

CFLAGS=-g -O2 -Wall -pedantic -std=gnu99 -mtune=native -pipe
CXXFLAGS=-g -O2 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L"$(LLVM_LOC)/lib" -L"$(GETTEXT_LOC)/lib" -Wl,-rpath,$(LLVM_LOC)/lib --sysroot="$(XC_LOC)" -lomp
CPPFLAGS=-I"$(GETTEXT_LOC)/include" -I"$(LLVM_LOC)/include" -I"$(OMP_LOC)/include" -isysroot "$(XC_LOC)" -Xclang -fopenmp

FC=$(GCC_LOC)/bin/gfortran
F77=$(GCC_LOC)/bin/gfortran
FLIBS=-L$(GCC_LOC)/lib/gcc/10/ -lm
```

```
> data(iris)
> library(fixest)
> summary(feols(Sepal.Length ~ Petal.Length | Species[Sepal.Width], iris))
OLS estimation, Dep. Var.: Sepal.Length
Observations: 150
Fixed-effects: Species: 3
Varying slopes: Sepal.Width (Species: 3)
Standard-errors: Clustered (Species)
             Estimate Std. Error t value Pr(>|t|)
Petal.Length 0.822045    0.10061  8.1706 0.014651 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.298903     Adj. R2: 0.863326
                 Within R2: 0.518738
>
```

**Comment by Asquidy** [comment]
@adamaltmejd Thanks. I think the problem is that it isn't able to do multi-thread operations, not that it doesn't run at all. Can you try the following?
```
 summary(feols(Sepal.Length ~ Petal.Length | Species[Sepal.Width], iris), nthreads = 4)
```

**Comment by adamaltmejd** [comment]
Oops! Forgot to add that part to the post:

```
> library(fixest)
> data(iris)
>  summary(feols(Sepal.Length ~ Petal.Length | Species[Sepal.Width], iris), nthreads = 4)
OLS estimation, Dep. Var.: Sepal.Length
Observations: 150
Fixed-effects: Species: 3
Varying slopes: Sepal.Width (Species: 3)
Standard-errors: Clustered (Species)
             Estimate Std. Error t value Pr(>|t|)
Petal.Length 0.822045    0.10061  8.1706 0.014651 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.298903     Adj. R2: 0.863326
                 Within R2: 0.518738
```

**Comment by lrberge** [comment]
@adamaltmejd you rock!

@Asquidy: could you check if it works for you? If so, I'll pin an issue describing the way to go for Mac users.

**Comment by Asquidy** [comment]
It still doesn't work. FYI, I'm using Big Sur and R 4.0.3.

**Comment by lrberge** [comment]
Too bad :-(, at least we know it can work w/t extra changes in the package for some Mac users.

**Comment by adamaltmejd** [comment]
Strange. Are you using R installed with Homebrew? And github fixest built from source? For example installed by running `remotes::install_github("lrberge/fixest")`? Did you get openMP to work with data.table and fst? Latest Homebrew R version is 4.0.4 so try updating.

**Comment by Asquidy** [comment]
I've tried many of these things (and yes data.table works). Unfortunately,
installing fixest from github doesn't work. I can't justify the time it
takes to try to debug this even more.

**Comment by adamaltmejd** [comment]
Yeah probably the use case where one wants to run code on own computer instead of server and really need multicore is quite rare.

**Comment by matthewgson** [comment]
Mac user here. Since CRAN on Mac uses Apple Xcode command line tools after R 4.0, which does not support OpenMP, you might want to compile the package from your own computer, not downloading the binary from CRAN. This can be done by adding `type="source"` in `install.packages()`. Seems `fixest` is running smoothly on my machine (Big Sur, R 4.0.3). I believe this will fix OpenMP issue with your `fst` as well (make sure CXX11 is defined on your .Makevars). Hope this helps!

**Comment by lrberge** [comment]
Thanks @matthewgson! Since the problem does not seem general but rather quite specific to the OP, I'm closing. Thanks all!

**Comment by adamaltmejd** [comment]
I can btw confirm that the Makefile posted above also works with the 4.1 big sur binary for arm M1 macs at least for me. Just make sure to build fixest from source.

**Comment by grantmcdermott** [comment]
@adamaltmejd's solution [above](https://github.com/lrberge/fixest/issues/63#issuecomment-806163771) has generally worked really well for me.

Just adding some info since I ran `brew update` today and got caught out by some broken symlinks following the OpenMP and LLVM updates. To fix, I needed to:
- Explicitly reinstall z3 `brew reinstall z3` (Adam, maybe worth adding z3 to your initial brew install call?)
- Update my compile flags (the brew output tells you to do this, but worth pointing out nonetheless since I think Homebrew's default location changed).

   ```sh
   export LDFLAGS="-L/usr/local/opt/llvm/lib"
   export CPPFLAGS="-I/usr/local/opt/llvm/include"
   export LDFLAGS="-L/usr/local/opt/libomp/lib"
   export CPPFLAGS="-I/usr/local/opt/libomp/include"
   ```

**Comment by Asquidy** [comment]
Can confirm that this now works!

**Comment by adamaltmejd** [comment]
Couple of things: 

It's unfortunately a recurring problem with compiled R packages. Whenever brew updates llvm and you try to install new R packages some of the dependencies will point to old libraries which will lead to compilation errors. Usually really annoying to identify which packages need to be rebuilt so i tend to just rebuild my whole R library.

The code above uses `brew --prefix llvm` because the brew directory can be in different places. On a clean install M1 mac its `/opt/homebrew/opt/llvm`. 

I would be careful about exporting those compile flags outside of R, not sure how that will work with other brew-compiled software that usually uses the built-in compilation toolchain.

**Comment by RoyalTS** [comment]
Does the above recipe still work for people or has it gone out of date over the last 18 months?

**Comment by grantmcdermott** [comment]
Still works for me, although I haven't tested on one of the newer Macs with the "M" silicon-based chips.

**Comment by adamaltmejd** [comment]
Same on an M1 with Sonoma.

**Comment by grantmcdermott** [comment]
Quick HU for folks on this thread that OpenMP multithreading should work out of the gate for Mac users now, following #615 and the release of `fixest` 0.14.0. No need to configure `~/.R/Makevars` etc. any more. Just grab the latest binary build of `fixest` and let 'er rip. I've tested with binary installs from both CRAN and R-universe and it's behaving as expected for me. (Please let us know if you experience differently!)

P.S. For any new readers of this thread, you'll need to install OpenMP on your system first. I recommend James Balumuta's simple install scripts [here](https://github.com/coatless-shell/openmp).

**Comment by adamaltmejd** [comment]
Hey! Thanks for this, saw it in the 0.14 release notes but had not tested. Not working for me with libomp installed via brew. But data.table is getting 5 threads automatically. Tried setting Makevars to only 

```
LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
```

like brew recommends and to

```
CPPFLAGS += -Xclang -fopenmp
LDFLAGS += -lomp
```

like in the script you posted. Will debug more later.

**Comment by grantmcdermott** [comment]
Hmmm, that's annoying. Can you share your session info @adamaltmejd? I'm on a new arm64 chip running R 4.5.2. Maybe there's some discrepancy here.

**Comment by adamaltmejd** [comment]
Claude figured it out for me. Seems like it did not work with PPM as the package repo. Works now on M5 mac after `install.packages("fixest", repos = "https://cloud.r-project.org", type = "binary")`.

**Comment by grantmcdermott** [comment]
@adamaltmejd FYI I filed an upstream P3M issue after being similarly caught out in an `rv` project. (Luckily your comment had made me aware that this could happen.) https://forum.posit.co/t/missing-openmp-support-for-p3m-macos-binaries-affects-data-table-fixest-and-likely-others/211094
